name: ci

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: hoff97/hikeandfly:latest
          cache-from: type=registry,ref=hoff97/hikeandfly:latest
          cache-to: type=inline
  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            # Stop running container
            docker stop hoff97hikeandfly
            # Remove old container and image, pull new image
            docker rm hoff97hikeandfly
            docker image rm hoff97/hikeandfly
            docker pull hoff97/hikeandfly:latest
            # Run a new container from a new image
            docker run -d \
              --restart always \
              --name hoff97hikeandfly \
              -p 80:80 \
              -p 443:443 \
              hoff97/hikeandfly:latest
