name: ci

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: hoff97/hikeandfly:latest
          cache-from: type=registry,ref=hoff97/hikeandfly:latest
          cache-to: type=inline
  deploy:
    name: "Deploy to server"
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/prod.key
          chmod 600 ~/.ssh/prod.key
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/prod.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSHKEY }}
          SSH_HOST: ${{ secrets.HOST }}

      - name: Stop and start the server
        run: ssh prod 'docker pull hoff97/hikeandfly:latest && docker stop hoff97hikeandfly && docker rm hoff97hikeandfly && docker image prune -f && docker run -d --restart always --name hoff97hikeandfly -v /root/data:/app/data -p 8080:8080 hoff97/hikeandfly:latest'
